/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.BorderLayout;
import java.util.ArrayList;
import modelo.clsCurso;
import vista.paneles_cursos.*;


public class jDialogCursos extends javax.swing.JDialog {

    private ArrayList<clsCurso> lstCursos;
    private jPanelCrearCursos panelCursos;
    private jPanelCrearModulo panelModulo;
    private jPanelImprimir panelImprimir;
    
    public jDialogCursos(java.awt.Frame parent, boolean modal,ArrayList<clsCurso> lstCursos) {
        super(parent, modal);
        this.lstCursos = lstCursos;
        this.panelCursos = new jPanelCrearCursos(this.lstCursos);
        this.panelModulo = new jPanelCrearModulo(this.lstCursos);
        this.panelImprimir = new jPanelImprimir(this.lstCursos);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelSuperior = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        jPanelIzquierdo = new javax.swing.JPanel();
        btnCrear = new javax.swing.JButton();
        btnModulos = new javax.swing.JButton();
        btnImprimir = new javax.swing.JButton();
        jPanelCentro = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 400));

        jPanelSuperior.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblTitulo.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        lblTitulo.setText("GESTIÓN DE CURSOS");
        jPanelSuperior.add(lblTitulo);

        getContentPane().add(jPanelSuperior, java.awt.BorderLayout.PAGE_START);

        jPanelIzquierdo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnCrear.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCrear.setText("CREAR");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        btnModulos.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnModulos.setText("MODULOS");
        btnModulos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModulosActionPerformed(evt);
            }
        });

        btnImprimir.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnImprimir.setText("IMRIMIR");
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelIzquierdoLayout = new javax.swing.GroupLayout(jPanelIzquierdo);
        jPanelIzquierdo.setLayout(jPanelIzquierdoLayout);
        jPanelIzquierdoLayout.setHorizontalGroup(
            jPanelIzquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelIzquierdoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelIzquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCrear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnModulos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnImprimir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelIzquierdoLayout.setVerticalGroup(
            jPanelIzquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelIzquierdoLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(btnCrear)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnModulos)
                .addGap(18, 18, 18)
                .addComponent(btnImprimir)
                .addContainerGap(134, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelIzquierdo, java.awt.BorderLayout.LINE_START);

        jPanelCentro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelCentro.setLayout(new java.awt.BorderLayout());
        getContentPane().add(jPanelCentro, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnModulosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModulosActionPerformed
        this.jPanelCentro.remove(this.panelCursos);
        this.jPanelCentro.remove(this.panelImprimir);
        this.jPanelCentro.add(this.panelModulo, BorderLayout.CENTER);
        this.jPanelCentro.revalidate();
        this.jPanelCentro.repaint();
    }//GEN-LAST:event_btnModulosActionPerformed

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        this.jPanelCentro.remove(this.panelImprimir);
        this.jPanelCentro.remove(this.panelModulo);
        this.jPanelCentro.add(this.panelCursos, BorderLayout.CENTER);
        this.jPanelCentro.revalidate();
        this.jPanelCentro.repaint();
    }//GEN-LAST:event_btnCrearActionPerformed

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        this.jPanelCentro.remove(this.panelCursos);
        this.jPanelCentro.remove(this.panelModulo);
        this.jPanelCentro.add(this.panelImprimir, BorderLayout.CENTER);
        this.jPanelCentro.revalidate();
        this.jPanelCentro.repaint();
    }//GEN-LAST:event_btnImprimirActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnModulos;
    private javax.swing.JPanel jPanelCentro;
    private javax.swing.JPanel jPanelIzquierdo;
    private javax.swing.JPanel jPanelSuperior;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
