/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import datos.clsGestionArchivo;
import java.awt.BorderLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import modelo.clsProfesor;
import vista.paneles_Profes.*;

/**
 *
 * @author freid
 */
public class jDialogProfes extends javax.swing.JDialog {

    private ArrayList<clsProfesor> lstProfes;
    private jPanelCrearProfe panelProfe;
    private jPanelImprimirProfe panelImprimir;
    
    public jDialogProfes(java.awt.Frame parent, boolean modal, ArrayList<clsProfesor> lstProfes) {
        super(parent, modal);
        this.lstProfes = lstProfes;
        this.panelProfe = new jPanelCrearProfe(this.lstProfes);
        this.panelImprimir = new jPanelImprimirProfe(this.lstProfes);
        initComponents();
    }
    
    private void eventCerrar(){
        String botones [] = {"Si, Salir","No, Salir"};
        int eleccion = JOptionPane.showOptionDialog(this, 
                "¿Desea Guardar los Datos Registrados y Salir?", 
                "Validación de Cierre", 0, 0, null, botones, this);
        if(eleccion==JOptionPane.YES_OPTION){
            clsGestionArchivo GA = new clsGestionArchivo();
            GA.escribirArchivoProfes(this.lstProfes);
        
            JOptionPane.showMessageDialog(this,
                    "Datos Guardados con Éxito",
                    "Gestion Escritura",
                    JOptionPane.INFORMATION_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelsuperior = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        panelizquierdo = new javax.swing.JPanel();
        btnCrear = new javax.swing.JButton();
        btnImprimir = new javax.swing.JButton();
        panelCentral = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 500));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        panelsuperior.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblTitulo.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblTitulo.setText("GESTIÓN DE PROFESORES");
        panelsuperior.add(lblTitulo);

        getContentPane().add(panelsuperior, java.awt.BorderLayout.PAGE_START);

        panelizquierdo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnCrear.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCrear.setText("CREAR");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        btnImprimir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnImprimir.setText("IMPRIMIR");
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelizquierdoLayout = new javax.swing.GroupLayout(panelizquierdo);
        panelizquierdo.setLayout(panelizquierdoLayout);
        panelizquierdoLayout.setHorizontalGroup(
            panelizquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelizquierdoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelizquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnImprimir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCrear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelizquierdoLayout.setVerticalGroup(
            panelizquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelizquierdoLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(btnCrear)
                .addGap(36, 36, 36)
                .addComponent(btnImprimir)
                .addContainerGap(142, Short.MAX_VALUE))
        );

        getContentPane().add(panelizquierdo, java.awt.BorderLayout.LINE_START);

        panelCentral.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelCentral.setLayout(new java.awt.BorderLayout());
        getContentPane().add(panelCentral, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        this.panelCentral.remove(this.panelImprimir);
        this.panelCentral.add(this.panelProfe,BorderLayout.CENTER);
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_btnCrearActionPerformed

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        this.panelCentral.remove(this.panelProfe);
        this.panelCentral.add(this.panelImprimir,BorderLayout.CENTER);
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_btnImprimirActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        eventCerrar();
    }//GEN-LAST:event_formWindowClosing

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel panelCentral;
    private javax.swing.JPanel panelizquierdo;
    private javax.swing.JPanel panelsuperior;
    // End of variables declaration//GEN-END:variables
}
