package vista;

import datos.clsGestionArchivo;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import modelo.*;

public class vtnPrincipal extends javax.swing.JFrame {

    private ArrayList<clsDeuda> lstDeudas;
    private ArrayList<clsCurso> lstCursos;
    private ArrayList<clsEstudiante> lstEstudiantes;
    private ArrayList<clsProfesor> lstProfes;
    
    public vtnPrincipal(ArrayList<clsProfesor> lstProfes) {
        this.lstDeudas = new ArrayList<>();
        this.lstCursos = new ArrayList<>();
        this.lstEstudiantes = new ArrayList<>();
        this.lstProfes = lstProfes;
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jpCentral = new javax.swing.JPanel();
        btnCursos = new javax.swing.JButton();
        btnEstudiantes = new javax.swing.JButton();
        btnDeudas = new javax.swing.JButton();
        btnPrpfesores = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        btnCursos.setText("CURSOS");
        btnCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCursosActionPerformed(evt);
            }
        });

        btnEstudiantes.setText("ESTUDIANTES");
        btnEstudiantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstudiantesActionPerformed(evt);
            }
        });

        btnDeudas.setText("DEUDAS");
        btnDeudas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeudasActionPerformed(evt);
            }
        });

        btnPrpfesores.setText("PROFESORES");
        btnPrpfesores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrpfesoresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpCentralLayout = new javax.swing.GroupLayout(jpCentral);
        jpCentral.setLayout(jpCentralLayout);
        jpCentralLayout.setHorizontalGroup(
            jpCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCentralLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(jpCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnEstudiantes, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                    .addComponent(btnDeudas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addGroup(jpCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnPrpfesores, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                    .addComponent(btnCursos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        jpCentralLayout.setVerticalGroup(
            jpCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCentralLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(jpCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCursos, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEstudiantes, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jpCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnPrpfesores, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(btnDeudas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(109, Short.MAX_VALUE))
        );

        getContentPane().add(jpCentral, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEstudiantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstudiantesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEstudiantesActionPerformed

    private void btnCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCursosActionPerformed
        jDialogCursos jdCursos = new jDialogCursos(this,false,this.lstCursos);
        jdCursos.setVisible(true);
    }//GEN-LAST:event_btnCursosActionPerformed

    private void btnDeudasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeudasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeudasActionPerformed

    private void btnPrpfesoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrpfesoresActionPerformed
        jDialogProfes jdProfes = new jDialogProfes(this,false, this.lstProfes);
        jdProfes.setVisible(true);
    }//GEN-LAST:event_btnPrpfesoresActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

    }//GEN-LAST:event_formWindowClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCursos;
    private javax.swing.JButton btnDeudas;
    private javax.swing.JButton btnEstudiantes;
    private javax.swing.JButton btnPrpfesores;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jpCentral;
    // End of variables declaration//GEN-END:variables
}
