/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.paneles_cursos;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import modelo.clsCurso;


public class jPanelCrearCursos extends javax.swing.JPanel {

     private ArrayList<clsCurso> lstCursos;
   
    public jPanelCrearCursos(ArrayList<clsCurso> lstCursos) {
        this.lstCursos = lstCursos;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCentral = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        lblSemestre = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtSemestre = new javax.swing.JTextField();
        btnCrear = new javax.swing.JButton();
        dcFecha = new com.toedter.calendar.JDateChooser();

        setLayout(new java.awt.BorderLayout());

        lblNombre.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        lblNombre.setText("Digite Nombre:");

        lblSemestre.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        lblSemestre.setText("Digite Semestre:");

        lblFecha.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        lblFecha.setText("Seleccione Fecha:");

        btnCrear.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCrear.setText("CREAR");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCentralLayout = new javax.swing.GroupLayout(jPanelCentral);
        jPanelCentral.setLayout(jPanelCentralLayout);
        jPanelCentralLayout.setHorizontalGroup(
            jPanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCentralLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombre)
                    .addComponent(lblSemestre)
                    .addComponent(lblFecha))
                .addGap(27, 27, 27)
                .addGroup(jPanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNombre)
                    .addComponent(txtSemestre)
                    .addComponent(dcFecha, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                    .addGroup(jPanelCentralLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(btnCrear)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanelCentralLayout.setVerticalGroup(
            jPanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCentralLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSemestre)
                    .addComponent(txtSemestre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFecha)
                    .addComponent(dcFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(btnCrear)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        add(jPanelCentral, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        if(this.txtNombre.getText().equalsIgnoreCase("") || 
                this.txtSemestre.getText().equalsIgnoreCase("")){
            JOptionPane.showMessageDialog(this, "Diligenciar todos los campos"
                    , "Validacion",JOptionPane.ERROR_MESSAGE);
        }else{
            clsCurso objCurso = new clsCurso();
            objCurso.setNombre(this.txtNombre.getText());
            objCurso.setSemestre(Integer.parseInt(this.txtSemestre.getText()));
            objCurso.setFecha(this.dcFecha.getCalendar());
        
            this.lstCursos.add(objCurso);
            JOptionPane.showMessageDialog(this, "Curso Agregado!");
            this.txtNombre.setText("");
            this.txtSemestre.setText("");
            this.dcFecha.setCalendar(null);
        }
    }//GEN-LAST:event_btnCrearActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrear;
    private com.toedter.calendar.JDateChooser dcFecha;
    private javax.swing.JPanel jPanelCentral;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblSemestre;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtSemestre;
    // End of variables declaration//GEN-END:variables
}
