/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.paneles_cursos;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import modelo.clsCurso;
import modelo.clsModulo;


public class jPanelImprimir extends javax.swing.JPanel {

    private ArrayList<clsCurso> lstCursos;
    
    public jPanelImprimir(ArrayList<clsCurso> lstCursos) {
        this.lstCursos = lstCursos;
        initComponents();
    }

    public int buscarCurso(){
        int posicion=-1;
        String nombre=this.txtNombre.getText();
        for(int i=0;i<this.lstCursos.size();i++){
            if(nombre.equalsIgnoreCase(this.lstCursos.get(i).getNombre())){
                posicion=i;
                break;
            }
        }
        return posicion;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCentral = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtPaneResultado = new javax.swing.JTextPane();

        setLayout(new java.awt.BorderLayout());

        jLabel1.setText("INFORMACION CURSOS");

        lblNombre.setText("Digite Nombre:");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        txtPaneResultado.setEditable(false);
        jScrollPane1.setViewportView(txtPaneResultado);

        javax.swing.GroupLayout jPanelCentralLayout = new javax.swing.GroupLayout(jPanelCentral);
        jPanelCentral.setLayout(jPanelCentralLayout);
        jPanelCentralLayout.setHorizontalGroup(
            jPanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCentralLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCentralLayout.createSequentialGroup()
                        .addComponent(lblNombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelCentralLayout.createSequentialGroup()
                                .addGap(0, 18, Short.MAX_VALUE)
                                .addComponent(jLabel1))
                            .addComponent(txtNombre))
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscar)
                        .addGap(67, 67, 67))
                    .addGroup(jPanelCentralLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanelCentralLayout.setVerticalGroup(
            jPanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCentralLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addGap(41, 41, 41)
                .addGroup(jPanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar)
                    .addComponent(lblNombre))
                .addGap(50, 50, 50)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        add(jPanelCentral, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        int posicion=buscarCurso();
        String informacion="";
        
        if(posicion>-1){
            SimpleDateFormat formato = new SimpleDateFormat("dd/MM/YYY");
            String fecha = formato.format(this.lstCursos.get(posicion).getFecha().getTime());
            informacion = informacion + "=======INFORMACION DEL CURSO======="+
                    "\n"+"Nombre: "+this.lstCursos.get(posicion).getNombre()+
                    "\nSemestre: "+this.lstCursos.get(posicion).getSemestre()+
                    "\nFecha: "+fecha+"\n";
            
            for(int i=0;i<this.lstCursos.get(posicion).getLstModulos().size();i++){
                clsModulo auxModulo = this.lstCursos.get(posicion).getLstModulos().get(i);
                informacion = informacion +"\tModulos\n"+
                        "\tTema: "+auxModulo.getTema()+
                        "\t\nPorcentaje: "+auxModulo.getPorcentaje()+"%"+"\n";
            }
            this.txtPaneResultado.setText(informacion);
        }else{
            JOptionPane.showMessageDialog(this, "Curso no Encontrado!",
                    "Busqueda",JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btnBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanelCentral;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextPane txtPaneResultado;
    // End of variables declaration//GEN-END:variables
}
