/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.paneles_Profes;

import datos.clsGestionArchivo;
import java.util.ArrayList;
import modelo.clsProfesor;

/**
 *
 * @author freid
 */
public class jPanelImprimirProfe extends javax.swing.JPanel {

    private ArrayList<clsProfesor> lstProfes;
    
    public jPanelImprimirProfe(ArrayList<clsProfesor> lstProfes) {
        this.lstProfes = lstProfes;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCentral = new javax.swing.JPanel();
        btnImprimirProfes = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        spContenedor = new javax.swing.JScrollPane();
        tablaProfes = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        btnImprimirProfes.setText("IMPRIMIR");
        btnImprimirProfes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirProfesActionPerformed(evt);
            }
        });

        lblTitulo.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblTitulo.setText("DATOS COMPLETOS DE PROFESORES");

        tablaProfes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Código", "Nombre", "Cargo", "Sueldo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        spContenedor.setViewportView(tablaProfes);

        javax.swing.GroupLayout panelCentralLayout = new javax.swing.GroupLayout(panelCentral);
        panelCentral.setLayout(panelCentralLayout);
        panelCentralLayout.setHorizontalGroup(
            panelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCentralLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblTitulo)
                .addGap(60, 60, 60))
            .addGroup(panelCentralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spContenedor)
                    .addGroup(panelCentralLayout.createSequentialGroup()
                        .addComponent(btnImprimirProfes)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelCentralLayout.setVerticalGroup(
            panelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCentralLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblTitulo)
                .addGap(33, 33, 33)
                .addComponent(btnImprimirProfes)
                .addGap(18, 18, 18)
                .addComponent(spContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        add(panelCentral, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnImprimirProfesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirProfesActionPerformed
        Object matriz [][] = new Object[this.lstProfes.size()][4];
        
        for(int i=0;i<this.lstProfes.size();i++){
            matriz[i][0] = this.lstProfes.get(i).getCodigo();
            matriz[i][1] = this.lstProfes.get(i).getNombre();
            matriz[i][2] = this.lstProfes.get(i).getCargo();
            matriz[i][3] = this.lstProfes.get(i).getSueldo();
        }
        
        tablaProfes.setModel(new javax.swing.table.DefaultTableModel(
        matriz, 
        new String [] {"Código","Nombre","Cargo","Sueldo"}
        ));
    }//GEN-LAST:event_btnImprimirProfesActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnImprimirProfes;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel panelCentral;
    private javax.swing.JScrollPane spContenedor;
    private javax.swing.JTable tablaProfes;
    // End of variables declaration//GEN-END:variables
}
