/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.paneles_Profes;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import modelo.*;

/**
 *
 * @author freid
 */
public class jPanelCrearProfe extends javax.swing.JPanel {

    private ArrayList<clsProfesor> lstProfes;
    
    public jPanelCrearProfe(ArrayList<clsProfesor> lstProfes) {
        this.lstProfes = lstProfes;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelCentral = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblCodigo = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblCargo = new javax.swing.JLabel();
        lblSueldo = new javax.swing.JLabel();
        btnCrearProfe = new javax.swing.JButton();
        txtCodigo = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        cbCargo = new javax.swing.JComboBox<>();
        txtSueldo = new javax.swing.JTextField();

        setLayout(new java.awt.BorderLayout());

        lblTitulo.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblTitulo.setText("FORMULARIO DE PROFESORES");

        lblCodigo.setText("Digite Codigo:");

        lblNombre.setText("Escriba Nombre:");

        lblCargo.setText("Seleccione Cargo:");

        lblSueldo.setText("Digite Sueldo:");

        btnCrearProfe.setText("CREAR");
        btnCrearProfe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearProfeActionPerformed(evt);
            }
        });

        cbCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Docente", "Coordinador", "Jefe" }));

        javax.swing.GroupLayout PanelCentralLayout = new javax.swing.GroupLayout(PanelCentral);
        PanelCentral.setLayout(PanelCentralLayout);
        PanelCentralLayout.setHorizontalGroup(
            PanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCentralLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(PanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitulo)
                    .addGroup(PanelCentralLayout.createSequentialGroup()
                        .addGroup(PanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCargo)
                            .addGroup(PanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblCodigo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblNombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(lblSueldo))
                        .addGap(18, 18, 18)
                        .addGroup(PanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnCrearProfe)
                            .addComponent(cbCargo, 0, 143, Short.MAX_VALUE)
                            .addComponent(txtCodigo)
                            .addComponent(txtNombre)
                            .addComponent(txtSueldo))))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        PanelCentralLayout.setVerticalGroup(
            PanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCentralLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblTitulo)
                .addGap(38, 38, 38)
                .addGroup(PanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigo)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(PanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCargo)
                    .addComponent(cbCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(PanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSueldo)
                    .addComponent(txtSueldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(btnCrearProfe)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        add(PanelCentral, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearProfeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearProfeActionPerformed
        try{
            long codigo = Long.parseLong(this.txtCodigo.getText());
            String nombre = this.txtNombre.getText();
            int posicionCargo = this.cbCargo.getSelectedIndex();
            cargoDocente aux;
            if(posicionCargo==0){
                aux = cargoDocente.Docente;
            }else{
                if(posicionCargo==1){
                    aux = cargoDocente.Coordinador;
                }else{
                    aux = cargoDocente.Jefe;
                }
            }

            float sueldo = Float.parseFloat(this.txtSueldo.getText());

            clsProfesor objProfesor = new clsProfesor(codigo, nombre, aux, sueldo);
            this.lstProfes.add(objProfesor);
            
            JOptionPane.showMessageDialog(this, "Profesor Creado");
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, 
                    "Error por conversion. Digite un numero",
                    "Validacion de datos",
                    JOptionPane.WARNING_MESSAGE);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, 
                    "Error General",
                    "Validacion",
                    JOptionPane.ERROR_MESSAGE);
        }
        finally{
            this.txtCodigo.setText("");
            this.txtNombre.setText("");
            this.cbCargo.setSelectedIndex(0);
            this.txtSueldo.setText("");
        }
    }//GEN-LAST:event_btnCrearProfeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelCentral;
    private javax.swing.JButton btnCrearProfe;
    private javax.swing.JComboBox<String> cbCargo;
    private javax.swing.JLabel lblCargo;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblSueldo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtSueldo;
    // End of variables declaration//GEN-END:variables
}
